/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogHowToAutomateWorkplaceTasksRouteImport } from './routes/blog.how-to-automate-workplace-tasks'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogHowToAutomateWorkplaceTasksRoute =
  BlogHowToAutomateWorkplaceTasksRouteImport.update({
    id: '/blog/how-to-automate-workplace-tasks',
    path: '/blog/how-to-automate-workplace-tasks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meeting': typeof MeetingRoute
  '/planner': typeof PlannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-automate-workplace-tasks': typeof BlogHowToAutomateWorkplaceTasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meeting': typeof MeetingRoute
  '/planner': typeof PlannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-automate-workplace-tasks': typeof BlogHowToAutomateWorkplaceTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meeting': typeof MeetingRoute
  '/planner': typeof PlannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/how-to-automate-workplace-tasks': typeof BlogHowToAutomateWorkplaceTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/email'
    | '/meeting'
    | '/planner'
    | '/sitemap.xml'
    | '/blog/how-to-automate-workplace-tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/email'
    | '/meeting'
    | '/planner'
    | '/sitemap.xml'
    | '/blog/how-to-automate-workplace-tasks'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/email'
    | '/meeting'
    | '/planner'
    | '/sitemap.xml'
    | '/blog/how-to-automate-workplace-tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  MeetingRoute: typeof MeetingRoute
  PlannerRoute: typeof PlannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogHowToAutomateWorkplaceTasksRoute: typeof BlogHowToAutomateWorkplaceTasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/how-to-automate-workplace-tasks': {
      id: '/blog/how-to-automate-workplace-tasks'
      path: '/blog/how-to-automate-workplace-tasks'
      fullPath: '/blog/how-to-automate-workplace-tasks'
      preLoaderRoute: typeof BlogHowToAutomateWorkplaceTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  MeetingRoute: MeetingRoute,
  PlannerRoute: PlannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogHowToAutomateWorkplaceTasksRoute: BlogHowToAutomateWorkplaceTasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
